---
- hosts: deploy-tomcat
  become: true
  become_user: root
  tasks:
    - name: Creates directory
      file:
        path: /home/skylab_priyadarshini/tomcat8.1
        state: directory
        owner: root
        group: root
        mode: 0775
    - name: Download tomcat
      get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.64/bin/apache-tomcat-8.5.64.tar.gz
        dest: /home/skylab_priyadarshini/tomcat8.1
        mode: 0755        
   # - name: Extract tomcat tar.gz
   #   unarchive:
   #      src: /home/skylab_priyadarshini/tomcat8.1/apache-tomcat-8.5.64.tar.gz
   #      dest: /home/skylab_priyadarshini/tomcat8.1
   #      mode: 0755
   #      recurse: yes
    - name: Extracting the tar file
      shell: cd /home/skylab_priyadarshini/tomcat8.1 && tar -xvzf apache-tomcat-8.5.64.tar.gz
    - name: Copy the playbook
      copy: src=/var/lib/jenkins/workspace/ansible-pipleline/target/myapp.war dest=/home/skylab_priyadarshini/tomcat8.1/apache-tomcat-8.5.64/webapps
    - name: Run Tomcat
      shell: cd /home/skylab_priyadarshini/tomcat8.1/apache-tomcat-8.5.64/bin && ./startup.sh
    
